### PR TITLE
v1: Add Scopegen and rename some package

### PR DESCRIPTION
**Pull request by nkristianto**
Add scopegen to replace current scope.go file. Rename some package name.

### CODE REVIEW

**Review by favadi — APPROVED** [review]
I can only review first 20 files, and they look OK for me. Couldn't review line by line as there are like 12000 lines added.

**Comment by nkristianto** [comment]
@favadi you can verify only the gunk file. the scopes are attached on the gunk file, and the result is in all.scopes.go file. just ignore all the other file

sorry for the big PR

**Review by ghazninattarshah — APPROVED** [review]
LGTM

**Comment by nkristianto** [comment]
please merge this after reviewers approved this PR https://github.com/brankas/openbank-services/pull/760

**Review by jwangsadinata — APPROVED** [review]
LGTM. Thanks for this @nkristianto

**Pull request merged**
