### PR TITLE
add initial Dockerfile

### PR DESCRIPTION
**Pull request by nkristianto**
This docker file will copy and build the openbank api into docker
image

### CODE REVIEW

**Review by cedric-parisi — APPROVED** [review]
LGTM

**Review by mvdan — COMMENTED** [review]
I assume this won't work once we remove the vendor folder, but we can fix that later.

Please fix the typo in the commit message and PR title; it says "initil".

**Comment by nkristianto** [comment]
> I assume this won't work once we remove the vendor folder, but we can fix that later.
> 
> Please fix the typo in the commit message and PR title; it says "initil".

ups.. sorry for the typo

**Comment by mvdan** [comment]
The commit still has the typo - please fix it.

**Comment by nkristianto** [comment]
> The commit still has the typo - please fix it.

ahh my bad. it's fixed dan

**Pull request merged**
